### ISSUE TITLE
"Join Scratch" page uses old color scheme

### ISSUE THREAD

**Issue by kelianor** [scratchfoundation/scratch-www#7758]
"Join Scratch" page uses blue colors instead of purple.
### Steps to Reproduce
1. Go to 'https://scratch.mit.edu/join'
2. Notice that background, tooltips and checkboxes use blue colors

**Comment by LuigiUI238** [comment]
There are a couple of Color Consitencies that I've discovered when using the website, and there is a forum for all the old color UI elements in the official topic.

**Comment by blazgocompany** [comment]
In `src/components/registration/steps.scss` `line 87`:
``` SCSS
input[type="radio"] {
            margin-right: 1rem;

            &:focus {
                transition: all .5s ease;
                border: 1px solid $ui-purple; /* Previously $ui-blue */
            }
 }
        
 
```

I couldn't test this so I didn't make a PR.
